#!/bin/sh

[ -n "$__CORE_SYSTEM_CACHED" ] && return
__CORE_SYSTEM_CACHED=1

. scripts/core/common.sh
. scripts/system-detect.sh

CORE_detect_system() {
    CORE_HOSTNAME="$HOSTNAME"
    CORE_OS="$OS"
    CORE_OS_TYPE="$OS_TYPE"
    CORE_OS_DISPLAY="$OS_DISPLAY"
    CORE_OS_ID="$OS_ID"
    CORE_OS_CODENAME="$OS_CODENAME"
    CORE_OS_DISTRO_VERSION="$OS_DISTRO_VERSION"
    CORE_OS_ARCH="$OS_ARCH"
    CORE_DOCKER_ARCH="$OS_DOCKER_ARCH"
    CORE_DOCKER_DISPLAY_ARCH="$OS_DOCKER_DISPLAY_ARCH"
    CORE_IS_LINUX="$OS_IS_LINUX"
    CORE_IS_DARWIN="$OS_IS_DARWIN"
    CORE_IS_ARM="$OS_IS_ARM"
    CORE_IS_WSL="$OS_IS_WSL"
}

CORE_detect_system

CORE_persist_system_env() {
    CORE_upsert_env "DEVICE_ID" "$CORE_HOSTNAME" "$ENV_SYSTEM_FILE"
    CORE_upsert_env "ARCH" "$CORE_DOCKER_ARCH" "$ENV_SYSTEM_FILE"
}

