services:
    repocket:
        container_name: repocket
        image: repocket/repocket
        restart: always
        environment:
            - RP_EMAIL=$REPOCKET_EMAIL
            - RP_API_KEY=$REPOCKET_API_KEY
        platform: linux/amd64
        profiles:
          - "${REPOCKET:-DISABLED}"
        dns:
            - 1.1.1.1
            - 8.8.8.8
        cpus: $CPU_LIMIT
        mem_limit: $RAM_LIMIT
        mem_reservation: $RAM_RESERVE

    proxyrack:
        container_name: proxyrack
        image: proxyrack/pop
        restart: always
        environment:
            - api_key=$PROXYRACK_API_KEY
            - device_name=$DEVICE_ID
            - UUID=$PROXYRACK_UUID
        platform: linux/amd64
        profiles:
          - "${PROXYRACK:-DISABLED}"
        dns:
            - 1.1.1.1
            - 8.8.8.8
        cpus: $CPU_LIMIT
        mem_limit: $RAM_LIMIT
        mem_reservation: $RAM_RESERVE

    proxylite:
        container_name: proxylite
        image: proxylite/proxyservice
        restart: always
        environment:
            - USER_ID=$PROXYLITE_USER_ID
        platform: linux/amd64
        profiles:
          - "${PROXYLITE:-DISABLED}"
        dns:
            - 1.1.1.1
            - 8.8.8.8
        cpus: $CPU_LIMIT
        mem_limit: $RAM_LIMIT
        mem_reservation: $RAM_RESERVE

    earnfm:
        container_name: earnfm
        image: earnfm/earnfm-client
        restart: always
        environment:
            - EARNFM_TOKEN=$EARNFM_TOKEN
        profiles:
          - "${EARNFM:-DISABLED}"
        dns:
            - 1.1.1.1
            - 8.8.8.8
        cpus: $CPU_LIMIT
        mem_limit: $RAM_LIMIT
        mem_reservation: $RAM_RESERVE

    bitping:
        container_name: bitping
        image: mrcolorrain/bitping
        restart: always
        hostname: $DEVICE_ID
        environment:
            - BITPING_EMAIL=$BITPING_EMAIL
            - BITPING_PASSWD=$BITPING_PASSWORD
        profiles:
          - "${BITPING:-DISABLED}"
        dns:
            - 1.1.1.1
            - 8.8.8.8
        volumes:
            - bitping-data:/root/.bitpingd
        cpus: $CPU_LIMIT
        mem_limit: $RAM_LIMIT
        mem_reservation: $RAM_RESERVE

    gaga-node:
        container_name: gaga-node
        image: xterna/gaga-node
        restart: always
        environment:
            - TOKEN=$GAGANODE_TOKEN
        profiles:
          - "${GAGANODE:-DISABLED}"
        dns:
            - 1.1.1.1
            - 8.8.8.8
        cpus: $CPU_LIMIT
        mem_limit: $RAM_LIMIT
        mem_reservation: $RAM_RESERVE

    nodepay:
        container_name: nodepay
        image: kellphy/nodepay:legacy
        restart: always
        environment:
            - NP_COOKIE=$NODEPAY_COOKIE
        profiles:
          - "${NODEPAY:-DISABLED}"
        dns:
            - 1.1.1.1
            - 8.8.8.8
        cpus: $CPU_LIMIT
        mem_limit: $RAM_LIMIT
        mem_reservation: $RAM_RESERVE

volumes:
    bitping-data:
