services:
    earnapp:
        container_name: earnapp
        image: ghcr.io/xterna/earnapp:alpine
        restart: always
        hostname: $DEVICE_ID
        labels:
            - project=standard
            - com.centurylinklabs.watchtower.scope=igm
        environment:
            - EARNAPP_UUID=${EARNAPP_DEVICE_UUID:-}
        profiles:
            - ${EARNAPP:-DISABLED}
        dns:
            - 1.1.1.1
            - 8.8.8.8
        volumes:
            - earnapp-data:/etc/earnapp
        cpus: $CPU_LIMIT
        mem_limit: $RAM_LIMIT
        mem_reservation: $RAM_RESERVE
        logging:
            driver: json-file
            options:
                max-size: 10k
                max-file: 1

    packetstream:
        container_name: packetstream
        image: packetstream/psclient
        restart: always
        hostname: $DEVICE_ID
        platform: ${PACKETSTREAM_PLATFORM:-}
        labels:
            - project=standard
            - com.centurylinklabs.watchtower.scope=igm
        environment:
            - CID=${PACKETSTREAM_CID:-}
        profiles:
            - ${PACKETSTREAM:-DISABLED}
        dns:
            - 1.1.1.1
            - 8.8.8.8
        cpus: $CPU_LIMIT
        mem_limit: $RAM_LIMIT
        mem_reservation: $RAM_RESERVE
        logging:
            driver: json-file
            options:
                max-size: 10k
                max-file: 1

    speedshare:
        container_name: speedshare
        image: mrcolorrain/speedshare
        restart: always
        hostname: $DEVICE_ID
        labels:
            - project=standard
            - com.centurylinklabs.watchtower.scope=igm
        environment:
            - CODE=${SPEEDSHARE_AUTH_CODE:-}
            - SPEEDSHARE_UUID=${SPEEDSHARE_UUID:-}
        platform: linux/amd64
        profiles:
            - ${SPEEDSHARE:-DISABLED}
        dns:
            - 1.1.1.1
            - 8.8.8.8
        cpus: $CPU_LIMIT
        mem_limit: $RAM_LIMIT
        mem_reservation: $RAM_RESERVE
        logging:
            driver: json-file
            options:
                max-size: 10k
                max-file: 1

    spide:
        container_name: spide
        image: xterna/spide-network
        restart: always
        hostname: $DEVICE_ID
        labels:
            - project=standard
            - com.centurylinklabs.watchtower.scope=igm
        environment:
            - ID=${SPIDE_MACHINE_ID:-}
        profiles:
            - ${SPIDE:-DISABLED}
        dns:
            - 1.1.1.1
            - 8.8.8.8
        cpus: $CPU_LIMIT
        mem_limit: $RAM_LIMIT
        mem_reservation: $RAM_RESERVE
        logging:
            driver: json-file
            options:
                max-size: 10k
                max-file: 1

    grass:
        container_name: grass
        image: mrcolorrain/grass-node
        restart: always
        hostname: $DEVICE_ID
        labels:
            - project=standard
            - com.centurylinklabs.watchtower.scope=igm
        environment:
            - USER_EMAIL=${GRASS_EMAIL:-}
            - USER_PASSWORD=${GRASS_PASSWORD:-}
        profiles:
            - ${GRASS:-DISABLED}
        dns:
            - 1.1.1.1
            - 8.8.8.8
        cpus: $ALT_MIN_CPU_LIMIT
        mem_limit: $RAM_LIMIT
        mem_reservation: $RAM_RESERVE
        logging:
            driver: json-file
            options:
                max-size: 10k
                max-file: 1

    nodepay:
        container_name: nodepay
        image: kellphy/nodepay
        restart: always
        hostname: $DEVICE_ID
        labels:
            - project=standard
            - com.centurylinklabs.watchtower.scope=igm
        environment:
            - NP_COOKIE=${NODEPAY_COOKIE:-}
        profiles:
            - ${NODEPAY:-DISABLED}
        dns:
            - 1.1.1.1
            - 8.8.8.8
        cpus: $CPU_LIMIT
        mem_limit: $RAM_LIMIT
        mem_reservation: $RAM_RESERVE
        logging:
            driver: json-file
            options:
                max-size: 10k
                max-file: 1

    network3:
        container_name: network3
        image: aron666/network3-ai
        restart: always
        hostname: $DEVICE_ID
        labels:
            - project=standard
        cap_add:
            - NET_ADMIN
        environment:
            - EMAIL=${NETWORK3_EMAIL:-}
        profiles:
            - ${NETWORK3:-DISABLED}
        dns:
            - 1.1.1.1
            - 8.8.8.8
        devices:
            - /dev/net/tun
        volumes:
            - network3-data:/usr/local/etc/wireguard
        cpus: $CPU_LIMIT
        mem_limit: $RAM_LIMIT
        mem_reservation: $RAM_RESERVE
        logging:
            driver: json-file
            options:
                max-size: 10k
                max-file: 1

    wipter:
        container_name: wipter
        image: ghcr.io/xterna/wipter
        restart: always
        hostname: $DEVICE_ID
        labels:
            - project=standard
            - com.centurylinklabs.watchtower.scope=igm
        environment:
            EMAIL: ${WIPTER_EMAIL:-}
            PASSWORD: ${WIPTER_PASSWORD:-}
            VNC_PASS: ${VNC_PASS:-}
        profiles:
            - ${WIPTER:-DISABLED}
        ports:
          - 8000:8080
        dns:
            - 1.1.1.1
            - 8.8.8.8
        cpus: $ALT_MIN_CPU_LIMIT
        mem_limit: $RAM_LIMIT
        mem_reservation: $RAM_RESERVE
        logging:
            driver: json-file
            options:
                max-size: 10k
                max-file: 1

volumes:
    earnapp-data:
    network3-data:
