services:
    earnapp:
        container_name: earnapp
        image: fazalfarhan01/earnapp:lite
        restart: always
        labels:
            - project=standard
        environment:
            - EARNAPP_UUID=${EARNAPP_DEVICE_UUID:-}
            - EARNAPP_TERM=yes
        profiles:
            - ${EARNAPP:-DISABLED}
        dns:
            - 1.1.1.1
            - 8.8.8.8
        volumes:
            - earnapp-data:/etc/earnapp
        healthcheck:
            disable: true
        cpus: $CPU_LIMIT
        mem_limit: $RAM_LIMIT
        mem_reservation: $RAM_RESERVE
        logging:
            driver: "json-file"
            options:
                max-size: "10k"
                max-file: "1"

    packetstream:
        container_name: packetstream
        image: packetstream/psclient
        restart: always
        labels:
            - project=standard
        environment:
            - CID=${PACKETSTREAM_CID:-}
        profiles:
            - ${PACKETSTREAM:-DISABLED}
        dns:
            - 1.1.1.1
            - 8.8.8.8
        cpus: $CPU_LIMIT
        mem_limit: $RAM_LIMIT
        mem_reservation: $RAM_RESERVE
        logging:
            driver: "json-file"
            options:
                max-size: "10k"
                max-file: "1"

    speedshare:
        container_name: speedshare
        image: mrcolorrain/speedshare
        restart: always
        labels:
            - project=standard
        hostname: $DEVICE_ID
        environment:
            - CODE=${SPEEDSHARE_AUTH_CODE:-}
            - SPEEDSHARE_UUID=${SPEEDSHARE_UUID:-}
        platform: linux/amd64
        profiles:
            - ${SPEEDSHARE:-DISABLED}
        network_mode: bridge
        dns:
            - 1.1.1.1
            - 8.8.8.8
        cpus: $CPU_LIMIT
        mem_limit: $RAM_LIMIT
        mem_reservation: $RAM_RESERVE
        logging:
            driver: "json-file"
            options:
                max-size: "10k"
                max-file: "1"

    spide:
        container_name: spide
        image: xterna/spide-network
        restart: always
        labels:
            - project=standard
        environment:
            - ID=${SPIDE_MACHINE_ID:-}
        profiles:
            - ${SPIDE:-DISABLED}
        dns:
            - 1.1.1.1
            - 8.8.8.8
        cpus: $CPU_LIMIT
        mem_limit: $RAM_LIMIT
        mem_reservation: $RAM_RESERVE
        logging:
            driver: "json-file"
            options:
                max-size: "10k"
                max-file: "1"

    grass:
        container_name: grass
        image: mrcolorrain/grass
        restart: always
        labels:
            - project=standard
        environment:
            - GRASS_USER=${GRASS_EMAIL:-}
            - GRASS_PASS=${GRASS_PASSWORD:-}
        profiles:
            - ${GRASS:-DISABLED}
        dns:
            - 1.1.1.1
            - 8.8.8.8
        cpus: $ALT_MIN_CPU_LIMIT
        mem_limit: $RAM_LIMIT
        mem_reservation: $RAM_RESERVE
        logging:
            driver: "json-file"
            options:
                max-size: "10k"
                max-file: "1"

    nodepay:
        container_name: nodepay
        image: kellphy/nodepay
        restart: always
        labels:
            - project=standard
        environment:
            - NP_COOKIE=${NODEPAY_COOKIE:-}
        profiles:
            - ${NODEPAY:-DISABLED}
        dns:
            - 1.1.1.1
            - 8.8.8.8
        cpus: $CPU_LIMIT
        mem_limit: $RAM_LIMIT
        mem_reservation: $RAM_RESERVE
        logging:
            driver: "json-file"
            options:
                max-size: "10k"
                max-file: "1"

volumes:
    earnapp-data:
