services:
    peer2profit:
        container_name: peer2profit
        image: xterna/peer2profit
        restart: always
        hostname: $DEVICE_ID
        labels:
            - project=standard
        environment:
            - P2P_EMAIL=${P2PROFIT_EMAIL:-}
        platform: linux/amd64
        profiles:
            - ${PEER2PROFIT:-DISABLED}
        dns:
            - 1.1.1.1
            - 8.8.8.8
        cpus: $CPU_LIMIT
        mem_limit: $RAM_LIMIT
        mem_reservation: $RAM_RESERVE
        logging:
            driver: "json-file"
            options:
                max-size: "10k"
                max-file: "1"

    traffmonetizer:
        container_name: traffmonetizer
        image: traffmonetizer/cli_v2${TRAFFMONETIZER_TAG:-}
        restart: always
        hostname: $DEVICE_ID
        labels:
            - project=standard
        command: >
            start accept
            --token ${TRAFFMONETIZER_TOKEN:-}
            --device-name ${DEVICE_ID:-}
        profiles:
            - ${TRAFFMONETIZER:-DISABLED}
        dns:
            - 1.1.1.1
            - 8.8.8.8
        cpus: $CPU_LIMIT
        mem_limit: $RAM_LIMIT
        mem_reservation: $RAM_RESERVE
        logging:
            driver: "json-file"
            options:
                max-size: "10k"
                max-file: "1"
