services:
    peer2profit:
        container_name: peer2profit
        image: xterna/peer2profit
        restart: always
        environment:
            - P2P_EMAIL=$P2PROFIT_EMAIL
        platform: linux/amd64
        dns:
            - 1.1.1.1
            - 8.8.8.8
        cpus: $CPU_LIMIT
        mem_limit: $RAM_LIMIT
        mem_reservation: $RAM_RESERVE

    traffmonetizer:
        container_name: tm
        image: traffmonetizer/cli_v2:$ARCH
        restart: always
        command: start accept --token $TRAFFMONETIZER_TOKEN --device-name $DEVICE_ID
        dns:
            - 1.1.1.1
            - 8.8.8.8
        cpus: $CPU_LIMIT
        mem_limit: $RAM_LIMIT
        mem_reservation: $RAM_RESERVE

    mysterium:
        container_name: myst
        image: mysteriumnetwork/myst
        restart: always
        cap_add:
            - NET_ADMIN
        command: service --agreed-terms-and-conditions
        ports:
            - 4449:4449
        dns:
            - 1.1.1.1
            - 8.8.8.8
        volumes:
            - $DATA_DIR/mysterium-node:/var/lib/mysterium-node
        cpus: $CPU_LIMIT
        mem_limit: $RAM_LIMIT
        mem_reservation: $RAM_RESERVE
