services:
    honeygain-pot:
        container_name: honeygain-pot
        image: ghcr.io/xterna/honeygain-pot${HONEYGAIN_SERVICE_TAG:-}
        restart: always
        labels:
            - project=standard
        environment:
            - EMAIL=${HONEYGAIN_EMAIL:-}
            - PASSWORD=${HONEYGAIN_PASSWORD:-}
        profiles:
            - ${HONEYGAIN_SERVICE:-DISABLED}
        dns:
            - 1.1.1.1
            - 8.8.8.8
        cpus: $ALT_MIN_CPU_LIMIT
        mem_limit: $RAM_LIMIT
        mem_reservation: $RAM_RESERVE
        logging:
            driver: "json-file"
            options:
                max-size: "10k"
                max-file: "1"

    bearshare-pot:
        container_name: bearshare-pot
        image: ghcr.io/xterna/bearshare-pot
        restart: always
        labels:
            - project=standard
        environment:
            - EMAIL=${BEARSHARE_EMAIL:-}
            - PASSWORD=${BEARSHARE_PASSWORD:-}
        profiles:
            - ${BEARSHARE_SERVICE:-DISABLED}
        dns:
            - 1.1.1.1
            - 8.8.8.8
        cpus: $ALT_MIN_CPU_LIMIT
        mem_limit: $RAM_LIMIT
        mem_reservation: $RAM_RESERVE
        logging:
            driver: "json-file"
            options:
                max-size: "10k"
                max-file: "1"

    packetshare-pot:
        container_name: packetshare-pot
        image: ghcr.io/xterna/packetshare-pot
        restart: always
        labels:
            - project=standard
        environment:
            - EMAIL=${PACKETSHARE_EMAIL:-}
            - PASSWORD=${PACKETSHARE_PASSWORD:-}
        profiles:
            - ${PACKETSHARE_SERVICE:-DISABLED}
        dns:
            - 1.1.1.1
            - 8.8.8.8
        cpus: $ALT_MIN_CPU_LIMIT
        mem_limit: $RAM_LIMIT
        mem_reservation: $RAM_RESERVE
        logging:
            driver: "json-file"
            options:
                max-size: "10k"
                max-file: "1"
