services:
    repocket:
        container_name: repocket
        image: repocket/repocket
        restart: always
        hostname: $DEVICE_ID
        labels:
            - project=standard
        environment:
            - RP_EMAIL=${REPOCKET_EMAIL:-}
            - RP_API_KEY=${REPOCKET_API_KEY:-}
        platform: linux/amd64
        profiles:
            - ${REPOCKET:-DISABLED}
        dns:
            - 1.1.1.1
            - 8.8.8.8
        cpus: $CPU_LIMIT
        mem_limit: $RAM_LIMIT
        mem_reservation: $RAM_RESERVE
        logging:
            driver: json-file
            options:
                max-size: 10k
                max-file: 1

    proxyrack:
        container_name: proxyrack
        image: proxyrack/pop
        restart: always
        hostname: $DEVICE_ID
        labels:
            - project=standard
        environment:
            - api_key=${PROXYRACK_API_KEY:-}
            - device_name=${DEVICE_ID:-}
            - UUID=${PROXYRACK_UUID:-}
        platform: linux/amd64
        profiles:
            - ${PROXYRACK:-DISABLED}
        dns:
            - 1.1.1.1
            - 8.8.8.8
        cpus: $CPU_LIMIT
        mem_limit: $RAM_LIMIT
        mem_reservation: $RAM_RESERVE
        logging:
            driver: json-file
            options:
                max-size: 10k
                max-file: 1

    proxylite:
        container_name: proxylite
        image: proxylite/proxyservice
        restart: always
        hostname: $DEVICE_ID
        labels:
            - project=standard
        environment:
            - USER_ID=${PROXYLITE_USER_ID:-}
        platform: linux/amd64
        profiles:
            - ${PROXYLITE:-DISABLED}
        dns:
            - 1.1.1.1
            - 8.8.8.8
        cpus: $CPU_LIMIT
        mem_limit: $RAM_LIMIT
        mem_reservation: $RAM_RESERVE
        logging:
            driver: json-file
            options:
                max-size: 10k
                max-file: 1

    earnfm:
        container_name: earnfm
        image: earnfm/earnfm-client
        restart: always
        hostname: $DEVICE_ID
        labels:
            - project=standard
        environment:
            - EARNFM_TOKEN=${EARNFM_TOKEN:-}
        profiles:
            - ${EARNFM:-DISABLED}
        dns:
            - 1.1.1.1
            - 8.8.8.8
        cpus: $CPU_LIMIT
        mem_limit: $RAM_LIMIT
        mem_reservation: $RAM_RESERVE
        logging:
            driver: json-file
            options:
                max-size: 10k
                max-file: 1

    mysterium:
        container_name: mysterium
        image: mysteriumnetwork/myst
        restart: always
        hostname: $DEVICE_ID
        labels:
            - project=standard
        cap_add:
            - NET_ADMIN
        command: service --agreed-terms-and-conditions
        profiles:
            - ${MYSTERIUM:-DISABLED}
        ports:
            - 4449:4449
        dns:
            - 1.1.1.1
            - 8.8.8.8
        volumes:
            - $DATA_DIR/mysterium-node:/var/lib/mysterium-node
        cpus: $CPU_LIMIT
        mem_limit: $RAM_LIMIT
        mem_reservation: $RAM_RESERVE
        logging:
            driver: json-file
            options:
                max-size: 10k
                max-file: 1

    bitping:
        container_name: bitping
        image: bitping/bitpingd
        restart: always
        hostname: $DEVICE_ID
        labels:
            - project=standard
        environment:
            BITPING_EMAIL: ${BITPING_EMAIL:-}
            BITPING_PASSWORD: ${BITPING_PASSWORD:-}
        profiles:
            - ${BITPING:-DISABLED}
        dns:
            - 1.1.1.1
            - 8.8.8.8
        volumes:
            - bitping-data:/root/.bitpingd
        cpus: $CPU_LIMIT
        mem_limit: $RAM_LIMIT
        mem_reservation: $RAM_RESERVE
        logging:
            driver: json-file
            options:
                max-size: 10k
                max-file: 1

    gaga-node:
        container_name: gaga-node
        image: xterna/gaga-node
        restart: always
        hostname: $DEVICE_ID
        labels:
            - project=standard
        environment:
            - TOKEN=${GAGANODE_TOKEN:-}
        profiles:
            - ${GAGANODE:-DISABLED}
        dns:
            - 1.1.1.1
            - 8.8.8.8
        cpus: $CPU_LIMIT
        mem_limit: $RAM_LIMIT
        mem_reservation: $RAM_RESERVE
        logging:
            driver: json-file
            options:
                max-size: 10k
                max-file: 1

    bearshare:
        container_name: bearshare
        image: bearshare/bearshare${BEARSHARE_TAG:-}
        restart: always
        hostname: $DEVICE_ID
        labels:
            - project=standard
        command: >
            -email=${BEARSHARE_EMAIL:-}
            -password=${BEARSHARE_PASSWORD:-}
        profiles:
            - ${BEARSHARE:-DISABLED}
        dns:
            - 1.1.1.1
            - 8.8.8.8
        cpus: $CPU_LIMIT
        mem_limit: $RAM_LIMIT
        mem_reservation: $RAM_RESERVE
        logging:
            driver: json-file
            options:
                max-size: 10k
                max-file: 1

volumes:
    bitping-data:
