services:
    earnapp:
        container_name: earnapp
        image: madereddy/earnapp
        restart: always
        environment:
            - EARNAPP_UUID=$EARNAPP_DEVICE_UUID
            - EARNAPP_TERM=yes
        platform: linux/amd64
        profiles:
          - "${EARNAPP:-DISABLED}"
        dns:
            - 1.1.1.1
            - 8.8.8.8
        volumes:
            - earnapp-data:/etc/earnapp
        cpus: $CPU_LIMIT
        mem_limit: $RAM_LIMIT
        mem_reservation: $RAM_RESERVE

    packetstream:
        container_name: packetstream
        image: packetstream/psclient
        restart: always
        environment:
            - CID=$PACKETSTREAM_CID
        profiles:
          - "${PACKETSTREAM:-DISABLED}"
        dns:
            - 1.1.1.1
            - 8.8.8.8
        cpus: $CPU_LIMIT
        mem_limit: $RAM_LIMIT
        mem_reservation: $RAM_RESERVE

    speedshare:
        container_name: speedshare
        image: mrcolorrain/speedshare
        restart: always
        hostname: $DEVICE_ID
        environment:
            - CODE=$SPEEDSHARE_AUTH_CODE
            - SPEEDSHARE_UUID=$SPEEDSHARE_UUID
        platform: linux/amd64
        profiles:
          - "${SPEEDSHARE:-DISABLED}"
        network_mode: bridge
        dns:
            - 1.1.1.1
            - 8.8.8.8
        cpus: $CPU_LIMIT
        mem_limit: $RAM_LIMIT
        mem_reservation: $RAM_RESERVE

    spide:
        container_name: spide
        image: xterna/spide-network
        restart: always
        environment:
            - ID=${SPIDE_MACHINE_ID:-}
        profiles:
          - "${SPIDE:-DISABLED}"
        dns:
            - 1.1.1.1
            - 8.8.8.8
        cpus: $CPU_LIMIT
        mem_limit: $RAM_LIMIT
        mem_reservation: $RAM_RESERVE

    grass:
        container_name: grass
        image: mrcolorrain/grass
        restart: always
        hostname: $DEVICE_ID
        environment:
            - GRASS_USER=$GRASS_EMAIL
            - GRASS_PASS=$GRASS_PASSWORD
        profiles:
          - "${GRASS:-DISABLED}"
        dns:
            - 1.1.1.1
            - 8.8.8.8
        cpus: $CPU_LIMIT
        mem_limit: $RAM_LIMIT
        mem_reservation: $RAM_RESERVE

volumes:
    earnapp-data:
