services:
    tun2socks:
        container_name: tun2socks
        image: xjasonlyu/tun2socks
        restart: always
        hostname: $DEVICE_ID
        labels:
            - project=proxy
            - com.centurylinklabs.watchtower.scope=igm
        environment:
            - LOGLEVEL=info
            - PROXY=${PROXY_URL:-}
            - TCP_AUTO_TUNING=1
            - MTU=1500
        cap_add:
            - NET_ADMIN
        security_opt:
            - no-new-privileges:true
        pids_limit: 200
        network_mode: bridge
        dns:
            - 1.1.1.1
            - 8.8.8.8
        ports:
            - 5000:8080
            - 6000:4449
        devices:
            - /dev/net/tun:/dev/net/tun
        cpus: $ALT_MIN_CPU_LIMIT
        mem_limit: $RAM_LIMIT
        mem_reservation: $RAM_RESERVE
        logging:
            driver: json-file
            options:
                max-size: 5k
                max-file: 1
